package app.mymultiverse.kmp.presentation.screens.home

/**
 * Canonical English values persisted for AI logic. UI labels come from string resources.
 */
object MealQuestionnaireValues {
    const val SKILL_SIMPLE = "Keep it simple"
    const val SKILL_AVERAGE = "Average home cook"
    const val SKILL_CHALLENGE = "I like a culinary challenge"
    const val LUNCH_LEFTOVERS = "I love leftovers for lunch"
    const val LUNCH_FRESH = "I prefer to cook lunches fresh/separately"
    const val GOAL_WEEK = "📋 Plan my entire week"
    const val GOAL_FRIDGE = "🧊 Tell me what to make with what's in my fridge right now"
    const val GOAL_GROCERY = "🛒 Just generate a quick grocery list"
    const val LOCATION_GPS = "Use GPS location"
    const val LOCATION_MANUAL = "Provide location manually"
    const val DIETARY_NONE = "None"
    const val TIME_UNDER_15 = "Under 15 mins"
    const val TIME_15_30 = "15-30 mins"
    const val TIME_30_60 = "30-60 mins"
}

object FinanceQuestionnaireValues {
    const val OPT_SPLIT_50_50 = "50/50 (Right down the middle)"
    const val OPT_SPLIT_PROPORTIONAL = "Proportional to income"
    const val OPT_SPLIT_CUSTOM = "Custom fixed percentages"
    const val OPT_SPLIT_ASSIGN = "Assign specific bills to specific people"
    const val OPT_SETTLE_VENMO = "We send Venmos/Zelles back and forth constantly"
    const val OPT_SETTLE_LUMP = "One person pays everything, and we calculate a lump sum at the end of the month"
    const val OPT_SETTLE_JOINT = "We have a shared joint account that we both fund, and bills auto-pay from there"
    const val OPT_BILL_HOUSING = "Housing (Rent / Mortgage)"
    const val OPT_BILL_UTILITIES = "Utilities (Electric, Water, Gas, Trash)"
    const val OPT_BILL_CONNECTIVITY = "Connectivity (Internet, Mobile/Cell plans)"
    const val OPT_BILL_SUBSCRIPTIONS = "Subscriptions (Netflix, Spotify, Gym, Costco, etc.)"
    const val OPT_BILL_INSURANCE = "Insurance (Car, Health, Home/Renter's)"
    const val OPT_BILL_KIDS_PETS = "Kids & Pets (Daycare, Tuition, Pet Insurance)"
    const val OPT_PAIN_LATE = "Forgetting when a bill is due (Late fees)"
    const val OPT_PAIN_NAGGING = "The awkwardness of nagging my partner to send their half"
    const val OPT_PAIN_FLUCTUATE = "Calculating who owes what when bills fluctuate (like electric/gas)"
    const val OPT_PAIN_PM = "Feeling like the Project Manager who has to log into 10 different sites"
    const val OPT_POOL_COMBINED = "Completely combined"
    const val OPT_POOL_SEPARATE = "Completely separate"
    const val OPT_POOL_MIX = "A mix (joint account for bills, separate for personal)"
    const val OPT_MANAGER_A = "Partner A does it all"
    const val OPT_MANAGER_B = "Partner B does it all"
    const val OPT_MANAGER_TOGETHER = "We try to do it together"
    const val OPT_MANAGER_CHAOTIC = "Honestly, it's a bit chaotic"
    const val OPT_ANNOY_BILLS_DUE = "Forgetting when bills are due"
    const val OPT_ANNOY_TRACKING = "Tracking who owes what"
    const val OPT_ANNOY_OVERSPEND = "Overspending on groceries/dining out"
    const val OPT_ANNOY_ARGUMENTS = "Arguments over personal spending"
    const val OPT_TALK_WRONG = "Only when something goes wrong"
    const val OPT_TALK_REGULAR = "Regularly (monthly/weekly check-ins)"
    const val OPT_TALK_AVOID = "Rarely/We avoid it"
    const val OPT_GOAL_EMERGENCY = "Building an emergency fund"
    const val OPT_GOAL_DEBT = "Paying off high-interest debt"
    const val OPT_GOAL_MILESTONE = "Saving for a big milestone (wedding, baby, house, vacation)"
    const val OPT_GOAL_PEACE = "Just gaining peace of mind"
    const val OPT_IRREGULAR_YES = "Yes, we save in advance"
    const val OPT_IRREGULAR_NO = "No, we just handle them as they hit our credit cards"
    const val SPLIT_PROPORTIONAL = OPT_SPLIT_PROPORTIONAL
    const val SPLIT_CUSTOM = OPT_SPLIT_CUSTOM
}

object WellnessQuestionnaireValues {
    const val OPT_LOVE_ACTS = "Acts of Service"
    const val OPT_LOVE_WORDS = "Words of Affirmation"
    const val OPT_LOVE_QUALITY = "Quality Time"
    const val OPT_LOVE_TOUCH = "Physical Touch"
    const val OPT_LOVE_GIFTS = "Receiving Gifts"
    const val OPT_TIME_5 = "5 minutes"
    const val OPT_TIME_15 = "15 minutes"
    const val OPT_TIME_30 = "30 minutes"
    const val OPT_TIME_60 = "1 hour"
    const val OPT_BUDGET_0 = "\$0"
    const val OPT_BUDGET_10 = "\$10"
    const val OPT_BUDGET_25 = "\$25"
    const val OPT_BUDGET_50 = "\$50"
    const val OPT_DRAIN_WORK = "Work"
    const val OPT_DRAIN_KIDS = "Kids"
    const val OPT_DRAIN_CHORES = "Chores"
    const val OPT_DRAIN_HEALTH = "Health"
    const val OPT_DRAIN_MONEY = "Money"
    const val OPT_DRAIN_FAMILY = "Family"
    const val OPT_DURATION_30 = "30 minutes"
    const val OPT_DURATION_60 = "1 hour"
    const val OPT_DURATION_120 = "2 hours"
    const val OPT_DURATION_EVENING = "All evening"
    const val DEFAULT_DATE_AVOID = "Watching a movie"
}

object LongTermQuestionnaireValues {
    const val OPT_MILESTONE_MOVE = "Moving to a new home"
    const val OPT_MILESTONE_RENO = "Renovation / Home Improvement"
    const val OPT_MILESTONE_EVENT = "Big Event (Wedding, milestone party, baby shower)"
    const val OPT_MILESTONE_TRANSITION = "Major life transition (New baby, career change, kids starting school)"
    const val OPT_MILESTONE_DECLUTTER = "Decluttering / Deep Organization (Garage, attic, etc.)"
    const val OPT_ROADBLOCK_TIME = "Time: We are too busy with daily life to focus on it."
    const val OPT_ROADBLOCK_ALIGNMENT = "Alignment: We aren't on the same page about the budget, style, or plan."
    const val OPT_ROADBLOCK_OVERWHELMED = "Overwhelmed: We don't know the correct order of steps to take."
    const val OPT_ROADBLOCK_ACCOUNTABILITY = "Accountability: We start, but things keep getting pushed to the back burner."
    const val OPT_TIMELINE_ASAP = "ASAP (Less than a month)"
    const val OPT_TIMELINE_MEDIUM = "Medium-term (1-6 months)"
    const val OPT_TIMELINE_LONG = "Long-term (6+ months / No rush)"
    const val OPT_BUDGET_TIGHT = "Tight / Bootstrapping (DIY all the way)"
    const val OPT_BUDGET_MODERATE = "Moderate (Some DIY, hiring pros for the big stuff)"
    const val OPT_BUDGET_FULL = "Full Service (We want to hire vendors/professionals)"
}
