#!/usr/bin/env python3
"""Append roadmap i18n keys to all locale strings.xml files."""

from pathlib import Path
from typing import Dict

ROOT = Path(__file__).resolve().parents[1] / "composeApp/src/commonMain/composeResources"

LOCALES = {
    "values": {
        "nutrition_sync_status_syncing": "Syncing shared nutrition...",
        "nutrition_sync_status_pending": "%1$d changes waiting to sync",
        "nutrition_sync_status_offline": "Shared sync offline — changes save locally",
        "auth_sign_out": "Sign out",
        "auth_pending_invites_title": "Sharing invite",
        "auth_pending_invites_subtitle": "You were invited to join %1$s.",
        "auth_pending_invites_accept": "Accept",
        "auth_pending_invites_decline": "Decline",
        "sharing_members_role_owner": "Owner",
        "sharing_members_role_editor": "Editor",
        "sharing_members_role_viewer": "Viewer",
        "sharing_members_role_label": "Role: %1$s",
        "sharing_members_owner_fallback": "Space owner",
        "sharing_members_manage_group": "Manage group",
        "sharing_members_group_members_title": "Group members",
        "sharing_members_add_to_group": "Add to group",
        "sharing_members_group_member_added": "Person added to the group.",
        "sharing_members_event_label": "Event label",
        "sharing_members_event_label_hint": "e.g. Ski weekend",
        "sharing_members_event_expires_label": "Ends on (YYYY-MM-DD)",
        "sharing_members_event_expires_required": "Pick an end date for trip or event groups.",
        "sharing_members_group_expired": "Expired",
        "sharing_members_invite_sent": "Invite sent. They can join after signing up.",
        "sharing_members_member_added": "Member added to this space.",
        "sharing_members_select_role": "Access level",
    },
    "values-fr": {
        "nutrition_sync_status_syncing": "Synchronisation nutrition partagée...",
        "nutrition_sync_status_pending": "%1$d modifications en attente de sync",
        "nutrition_sync_status_offline": "Sync partagée hors ligne — modifications locales",
        "auth_sign_out": "Se déconnecter",
        "auth_pending_invites_title": "Invitation de partage",
        "auth_pending_invites_subtitle": "Vous êtes invité à rejoindre %1$s.",
        "auth_pending_invites_accept": "Accepter",
        "auth_pending_invites_decline": "Refuser",
        "sharing_members_role_owner": "Propriétaire",
        "sharing_members_role_editor": "Éditeur",
        "sharing_members_role_viewer": "Lecteur",
        "sharing_members_role_label": "Rôle : %1$s",
        "sharing_members_owner_fallback": "Propriétaire de l'espace",
        "sharing_members_manage_group": "Gérer le groupe",
        "sharing_members_group_members_title": "Membres du groupe",
        "sharing_members_add_to_group": "Ajouter au groupe",
        "sharing_members_group_member_added": "Personne ajoutée au groupe.",
        "sharing_members_event_label": "Libellé de l'événement",
        "sharing_members_event_label_hint": "ex. Week-end ski",
        "sharing_members_event_expires_label": "Fin le (AAAA-MM-JJ)",
        "sharing_members_event_expires_required": "Choisissez une date de fin pour les groupes événement.",
        "sharing_members_group_expired": "Expiré",
        "sharing_members_invite_sent": "Invitation envoyée. Ils pourront rejoindre après inscription.",
        "sharing_members_member_added": "Membre ajouté à cet espace.",
        "sharing_members_select_role": "Niveau d'accès",
    },
    "values-es": {
        "nutrition_sync_status_syncing": "Sincronizando nutrición compartida...",
        "nutrition_sync_status_pending": "%1$d cambios pendientes de sincronizar",
        "nutrition_sync_status_offline": "Sincronización sin conexión — cambios locales",
        "auth_sign_out": "Cerrar sesión",
        "auth_pending_invites_title": "Invitación para compartir",
        "auth_pending_invites_subtitle": "Te invitaron a unirte a %1$s.",
        "auth_pending_invites_accept": "Aceptar",
        "auth_pending_invites_decline": "Rechazar",
        "sharing_members_role_owner": "Propietario",
        "sharing_members_role_editor": "Editor",
        "sharing_members_role_viewer": "Lector",
        "sharing_members_role_label": "Rol: %1$s",
        "sharing_members_owner_fallback": "Propietario del espacio",
        "sharing_members_manage_group": "Gestionar grupo",
        "sharing_members_group_members_title": "Miembros del grupo",
        "sharing_members_add_to_group": "Añadir al grupo",
        "sharing_members_group_member_added": "Persona añadida al grupo.",
        "sharing_members_event_label": "Etiqueta del evento",
        "sharing_members_event_label_hint": "p. ej. Fin de semana de esquí",
        "sharing_members_event_expires_label": "Termina el (AAAA-MM-DD)",
        "sharing_members_event_expires_required": "Elige una fecha de fin para grupos de viaje o evento.",
        "sharing_members_group_expired": "Caducado",
        "sharing_members_invite_sent": "Invitación enviada. Podrán unirse tras registrarse.",
        "sharing_members_member_added": "Miembro añadido a este espacio.",
        "sharing_members_select_role": "Nivel de acceso",
    },
    "values-de": {
        "nutrition_sync_status_syncing": "Geteilte Ernährung wird synchronisiert...",
        "nutrition_sync_status_pending": "%1$d Änderungen warten auf Sync",
        "nutrition_sync_status_offline": "Geteilter Sync offline — lokale Änderungen",
        "auth_sign_out": "Abmelden",
        "auth_pending_invites_title": "Freigabe-Einladung",
        "auth_pending_invites_subtitle": "Du wurdest eingeladen, %1$s beizutreten.",
        "auth_pending_invites_accept": "Annehmen",
        "auth_pending_invites_decline": "Ablehnen",
        "sharing_members_role_owner": "Besitzer",
        "sharing_members_role_editor": "Bearbeiter",
        "sharing_members_role_viewer": "Betrachter",
        "sharing_members_role_label": "Rolle: %1$s",
        "sharing_members_owner_fallback": "Space-Besitzer",
        "sharing_members_manage_group": "Gruppe verwalten",
        "sharing_members_group_members_title": "Gruppenmitglieder",
        "sharing_members_add_to_group": "Zur Gruppe hinzufügen",
        "sharing_members_group_member_added": "Person zur Gruppe hinzugefügt.",
        "sharing_members_event_label": "Ereignisbezeichnung",
        "sharing_members_event_label_hint": "z. B. Ski-Wochenende",
        "sharing_members_event_expires_label": "Endet am (JJJJ-MM-TT)",
        "sharing_members_event_expires_required": "Wähle ein Enddatum für Reise- oder Eventgruppen.",
        "sharing_members_group_expired": "Abgelaufen",
        "sharing_members_invite_sent": "Einladung gesendet. Beitritt nach Registrierung möglich.",
        "sharing_members_member_added": "Mitglied zum Space hinzugefügt.",
        "sharing_members_select_role": "Zugriffsstufe",
    },
    "values-it": {
        "nutrition_sync_status_syncing": "Sincronizzazione nutrizione condivisa...",
        "nutrition_sync_status_pending": "%1$d modifiche in attesa di sync",
        "nutrition_sync_status_offline": "Sync condivisa offline — modifiche locali",
        "auth_sign_out": "Esci",
        "auth_pending_invites_title": "Invito di condivisione",
        "auth_pending_invites_subtitle": "Sei stato invitato a unirti a %1$s.",
        "auth_pending_invites_accept": "Accetta",
        "auth_pending_invites_decline": "Rifiuta",
        "sharing_members_role_owner": "Proprietario",
        "sharing_members_role_editor": "Editor",
        "sharing_members_role_viewer": "Visualizzatore",
        "sharing_members_role_label": "Ruolo: %1$s",
        "sharing_members_owner_fallback": "Proprietario dello spazio",
        "sharing_members_manage_group": "Gestisci gruppo",
        "sharing_members_group_members_title": "Membri del gruppo",
        "sharing_members_add_to_group": "Aggiungi al gruppo",
        "sharing_members_group_member_added": "Persona aggiunta al gruppo.",
        "sharing_members_event_label": "Etichetta evento",
        "sharing_members_event_label_hint": "es. Weekend sci",
        "sharing_members_event_expires_label": "Termina il (AAAA-MM-GG)",
        "sharing_members_event_expires_required": "Scegli una data di fine per gruppi viaggio o evento.",
        "sharing_members_group_expired": "Scaduto",
        "sharing_members_invite_sent": "Invito inviato. Potranno unirsi dopo la registrazione.",
        "sharing_members_member_added": "Membro aggiunto a questo spazio.",
        "sharing_members_select_role": "Livello di accesso",
    },
    "values-ar": {
        "nutrition_sync_status_syncing": "جارٍ مزامنة التغذية المشتركة...",
        "nutrition_sync_status_pending": "%1$d تغييرات بانتظار المزامنة",
        "nutrition_sync_status_offline": "المزامنة المشتركة غير متصلة — التغييرات محلية",
        "auth_sign_out": "تسجيل الخروج",
        "auth_pending_invites_title": "دعوة مشاركة",
        "auth_pending_invites_subtitle": "تمت دعوتك للانضمام إلى %1$s.",
        "auth_pending_invites_accept": "قبول",
        "auth_pending_invites_decline": "رفض",
        "sharing_members_role_owner": "المالك",
        "sharing_members_role_editor": "محرر",
        "sharing_members_role_viewer": "مشاهد",
        "sharing_members_role_label": "الدور: %1$s",
        "sharing_members_owner_fallback": "مالك المساحة",
        "sharing_members_manage_group": "إدارة المجموعة",
        "sharing_members_group_members_title": "أعضاء المجموعة",
        "sharing_members_add_to_group": "إضافة إلى المجموعة",
        "sharing_members_group_member_added": "تمت إضافة الشخص إلى المجموعة.",
        "sharing_members_event_label": "تسمية الحدث",
        "sharing_members_event_label_hint": "مثال: عطلة تزلج",
        "sharing_members_event_expires_label": "ينتهي في (YYYY-MM-DD)",
        "sharing_members_event_expires_required": "اختر تاريخ انتهاء لمجموعات الرحلات أو الأحداث.",
        "sharing_members_group_expired": "منتهٍ",
        "sharing_members_invite_sent": "تم إرسال الدعوة. يمكنهم الانضمام بعد التسجيل.",
        "sharing_members_member_added": "تمت إضافة العضو إلى هذه المساحة.",
        "sharing_members_select_role": "مستوى الوصول",
    },
    "values-ar-rSA": {
        "nutrition_sync_status_syncing": "جارٍ مزامنة التغذية المشتركة...",
        "nutrition_sync_status_pending": "%1$d تغييرات بانتظار المزامنة",
        "nutrition_sync_status_offline": "المزامنة المشتركة غير متصلة — التغييرات محلية",
        "auth_sign_out": "تسجيل الخروج",
        "auth_pending_invites_title": "دعوة مشاركة",
        "auth_pending_invites_subtitle": "تمت دعوتك للانضمام إلى %1$s.",
        "auth_pending_invites_accept": "قبول",
        "auth_pending_invites_decline": "رفض",
        "sharing_members_role_owner": "المالك",
        "sharing_members_role_editor": "محرر",
        "sharing_members_role_viewer": "مشاهد",
        "sharing_members_role_label": "الدور: %1$s",
        "sharing_members_owner_fallback": "مالك المساحة",
        "sharing_members_manage_group": "إدارة المجموعة",
        "sharing_members_group_members_title": "أعضاء المجموعة",
        "sharing_members_add_to_group": "إضافة إلى المجموعة",
        "sharing_members_group_member_added": "تمت إضافة الشخص إلى المجموعة.",
        "sharing_members_event_label": "تسمية الحدث",
        "sharing_members_event_label_hint": "مثال: عطلة تزلج",
        "sharing_members_event_expires_label": "ينتهي في (YYYY-MM-DD)",
        "sharing_members_event_expires_required": "اختر تاريخ انتهاء لمجموعات الرحلات أو الأحداث.",
        "sharing_members_group_expired": "منتهٍ",
        "sharing_members_invite_sent": "تم إرسال الدعوة. يمكنهم الانضمام بعد التسجيل.",
        "sharing_members_member_added": "تمت إضافة العضو إلى هذه المساحة.",
        "sharing_members_select_role": "مستوى الوصول",
    },
    "values-nap": {
        "nutrition_sync_status_syncing": "Sto sincronizzanno 'a nutrizione condivisa...",
        "nutrition_sync_status_pending": "%1$d cagnature aspettanno 'a sync",
        "nutrition_sync_status_offline": "Sync shared offline — cagnature locale",
        "auth_sign_out": "Scì 'o sistema",
        "auth_pending_invites_title": "Invito 'e condivisione",
        "auth_pending_invites_subtitle": "T'han invitato a %1$s.",
        "auth_pending_invites_accept": "Accetta",
        "auth_pending_invites_decline": "Rifiuta",
        "sharing_members_role_owner": "Proprietario",
        "sharing_members_role_editor": "Editor",
        "sharing_members_role_viewer": "Chi guarda",
        "sharing_members_role_label": "Ruolo: %1$s",
        "sharing_members_owner_fallback": "Proprietario d' 'o spazio",
        "sharing_members_manage_group": "Gestisce 'o gruppo",
        "sharing_members_group_members_title": "Membri d' 'o gruppo",
        "sharing_members_add_to_group": "Aggiunge a 'o gruppo",
        "sharing_members_group_member_added": "Persona aggiunta a 'o gruppo.",
        "sharing_members_event_label": "Etichetta evento",
        "sharing_members_event_label_hint": "es. Weekend sci",
        "sharing_members_event_expires_label": "Finisce 'o (AAAA-MM-GG)",
        "sharing_members_event_expires_required": "Piglia 'na data 'e fine pe' gruppi viaggio o evento.",
        "sharing_members_group_expired": "Scaduto",
        "sharing_members_invite_sent": "Invito mandato. Pònno unì dopo 'a registrazione.",
        "sharing_members_member_added": "Membro aggiunto a stu spazio.",
        "sharing_members_select_role": "Livello 'e accesso",
    },
}


def append_strings(locale_dir: str, entries: Dict[str, str]) -> None:
    path = ROOT / locale_dir / "strings.xml"
    text = path.read_text(encoding="utf-8")
    if "</resources>" not in text:
        raise RuntimeError(f"Invalid strings.xml: {path}")
    block = "\n".join(
        f'    <string name="{key}">{value}</string>' for key, value in entries.items()
    )
    updated = text.replace("</resources>", f"{block}\n</resources>")
    path.write_text(updated, encoding="utf-8")


def main() -> None:
    for locale, entries in LOCALES.items():
        append_strings(locale, entries)
        print(f"Updated {locale}")


if __name__ == "__main__":
    main()
