#!/usr/bin/env bash
# Creates a dated IP evidence bundle (logos + git provenance manifest).
# Run from repo root: ./scripts/create-ip-evidence-archive.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATE="$(date +%Y-%m-%d)"
OUT="${ROOT}/docs/ip-evidence/archive-${DATE}"
LOGO_DIR="${OUT}/logos"

mkdir -p "${LOGO_DIR}"

echo "==> Copying logo assets to ${LOGO_DIR}"
cp "${ROOT}/web/brand/"*.png "${LOGO_DIR}/" 2>/dev/null || true
if [[ -f "${ROOT}/composeApp/src/commonMain/composeResources/drawable/ammo_round_logo.webp" ]]; then
  cp "${ROOT}/composeApp/src/commonMain/composeResources/drawable/ammo_round_logo.webp" "${LOGO_DIR}/"
fi
if [[ -f "${ROOT}/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/app-icon-1024.png" ]]; then
  cp "${ROOT}/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/app-icon-1024.png" "${LOGO_DIR}/" 2>/dev/null || true
fi

MANIFEST="${OUT}/MANIFEST.md"
{
  echo "# IP evidence manifest — ${DATE}"
  echo
  echo "Generated by \`scripts/create-ip-evidence-archive.sh\`. Store a copy outside the repo (cloud backup, notary, or lawyer file)."
  echo
  echo "## Repository"
  echo "- Path: \`${ROOT}\`"
  echo "- HEAD: \`$(git -C "${ROOT}" rev-parse HEAD)\`"
  echo "- Branch: \`$(git -C "${ROOT}" rev-parse --abbrev-ref HEAD)\`"
  echo "- Commit date: \`$(git -C "${ROOT}" log -1 --format=%ci)\`"
  echo
  echo "## Release tags (newest first)"
  echo '```'
  git -C "${ROOT}" tag -l 'v*' --sort=-version:refname | head -25 || true
  echo '```'
  echo
  echo "## Logo file history (web/brand)"
  echo '```'
  git -C "${ROOT}" log --follow --format='%h %ci %s' -- web/brand/ | head -15 || true
  echo '```'
  echo
  echo "## Bundled files"
  ls -la "${LOGO_DIR}"
  echo
  echo "## Rights holder"
  echo "Roberto Cornano (MyMultiverse) — see COPYRIGHT and docs/IP.md"
} > "${MANIFEST}"

ARCHIVE="${OUT}/ip-evidence-${DATE}.tar.gz"
tar -czf "${ARCHIVE}" -C "${OUT}" logos MANIFEST.md

echo "==> Created:"
echo "    ${MANIFEST}"
echo "    ${ARCHIVE}"
echo "==> Copy ${ARCHIVE} to secure storage (not required in git)."
